var dataSubCategory = {
    1: [
            {id: 1, nombre: "Marca Líder"},
            {id: 2, nombre: "Empresa Grande"},
            {id: 3, nombre: "PyME"},
            {id: 4, nombre: "Micro Empresa / Emprendimiento"},
            {id: 5, nombre: "Institución / ONG"},
    ],
    20: [
        {id: 6, nombre: "Marca Líder"},
        {id: 7, nombre: "Android"},
        {id: 8, nombre: "IOS"},
        {id: 9, nombre: "Desktop"},
    ],
    36: [
        {id: 10, nombre: "Pay Per Click (PPC)"},
        {id: 11, nombre: "Otra"},
    ],
    43: [
        { id: 12, nombre: "Website" },
        { id: 13, nombre: "Landing Page" },
        { id: 14, nombre: "Blog" },
        { id: 15, nombre: "Mail" },
        { id: 16, nombre: "Arreglo de website (bug)" },
        { id: 17, nombre: "Otro" },
    ],

};
var dataCategory = {
"marketing": [
    {id: 1, nombre: "Desarrollo de Negocio Digital"},
    {id: 2, nombre: "Marca e Imagen Corporativa  / Branding"},
    {id: 3, nombre: "Estrategia de Contenidos y Comunicación"},
    {id: 4, nombre: "Marketing de Social Media"},
    {id: 5, nombre: "Reputación on line"},
    {id: 6, nombre: "Estrategia de Crecimiento (Growth Hacking)"},
    {id: 7, nombre: "Estrategia de Experiencia de Consumidor"},
    {id: 8, nombre: "Generación de Prospectos (Leads)"},
    {id: 9, nombre: "Gestión de Campaña Digital"},
    {id: 10, nombre: "Optimización en Buscadores (SEO)"},
    {id: 11, nombre: "Marketing en Buscadores (SEM)"},
    {id: 12, nombre: "Estrategia de Ventas on line"},
    {id: 13, nombre: "Relaciones Públicas"},
    {id: 14, nombre: "Marketing de Influencers"},
    {id: 15, nombre: "Investigación y Análisis de Mercado"}
],
"diseno": [
    {id: 18, nombre: "Creación de Marca e Identidad Corporativa"},
    {id: 19, nombre: "Diseño Web "},
    {id: 20, nombre: "Diseño de Aplicación"},
    {id: 21, nombre: "Diseño UX: Experiencia de Usuario"},
    {id: 22, nombre: "Diseño Gráfico"},
    {id: 23, nombre: "Diseño Editorial"},
    {id: 24, nombre: "Diseño Industrial"},
    {id: 25, nombre: "Diseño de Indumentaria y Moda"},
    {id: 26, nombre: "Redacción"},
    {id: 27, nombre: "Traducción a idiomas"},
    {id: 28, nombre: "Fotografía"},
    {id: 29, nombre: "Ilustraciones"},
    {id: 30, nombre: "Animaciones"},
    {id: 31, nombre: "Video"},
    {id: 32, nombre: "Audio y Sonido"},
],
"publicidad": [
    {id: 33, nombre: "Creatividad Publicitaria"},
    {id: 34, nombre: "Planificación de Medios"},
    {id: 35, nombre: "Publicidad Digital"},
    {id: 36, nombre: "Gestión de Campaña Publicitaria"},
    {id: 37, nombre: "Publicidad en Redes Sociales (Social Ads)"},
    {id: 38, nombre: "Publicidad BTL"},
    {id: 39, nombre: "Eventos"},
    {id: 40, nombre: "Prensa"},
    {id: 41, nombre: "Estrategia multiformato 360"},           
],
"programacion": [
    {id: 42, nombre: "Interfaz de Usuario - Diseño UI / Front-End"},
    {id: 43, nombre: "Programación Web"},
    {id: 44, nombre: "Plataforma de Gestión de Contenidos (CMS)"},
    {id: 45, nombre: "Desarrollo de Aplicaciones"},
    {id: 46, nombre: "Integración con API’s"},
    {id: 47, nombre: "Comercio Electrónico"},
    {id: 48, nombre: "Juegos"},
    {id: 49, nombre: "Control de Calidad"},
    {id: 50, nombre: "Sistemas"},
    {id: 51, nombre: "Redes"},
    {id: 52, nombre: "Seguridad Informática"},
    {id: 53, nombre: "Inteligencia de Negocios / BI (Business Intelligence)"},
    {id: 54, nombre: "Soporte"},
]
};